add tensorboard callback #3
it fails with error
<Error in callback_tensorboard(log_dir = paste0("logs/fit/", descriptor,  :
  embeddings_data requires keras >= 2.2. Please update with install_keras()>

tried running install_keras() (with various options including tensorflow = "gpu") and always get error:
<Creating virtualenv for TensorFlow at  /opt/virtualenvs/r-tensorflow
Traceback (most recent call last):
  File "/opt/virtualenvs/r-tensorflow/lib/python3.5/site-packages/virtualenv.py", line 2610, in <module>
    main()
  File "/opt/virtualenvs/r-tensorflow/lib/python3.5/site-packages/virtualenv.py", line 834, in main
    symlink=options.symlink,
  File "/opt/virtualenvs/r-tensorflow/lib/python3.5/site-packages/virtualenv.py", line 1112, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/opt/virtualenvs/r-tensorflow/lib/python3.5/site-packages/virtualenv.py", line 1385, in install_python
    mkdir(lib_dir)
  File "/opt/virtualenvs/r-tensorflow/lib/python3.5/site-packages/virtualenv.py", line 394, in mkdir
    os.makedirs(at_path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/virtualenvs/r-tensorflow/lib/python2.7'
Running virtualenv with interpreter /usr/bin/python
Error: Error 1 occurred creating virtualenv at /opt/virtualenvs/r-tensorflow>